name: Keep Render Alive

on:
  schedule:
    - cron: '0 * * * *'   # 每小時一次
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Simulate every 5-min ping for 30 minutes
      run: |
        for i in {1..12}; do
          echo "[$(date)] Ping #$i"
          curl -m 30 https://linebotpipibear.onrender.com || echo "Failed"
          sleep 300
        done
